/** Generates only static public assets; never publishes source, docs, or worker code. */
import { build } from 'esbuild';
import { readFile, readdir, mkdir, writeFile, copyFile } from 'node:fs/promises';
import { resolve, dirname, basename } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';
import { validateSnapshot } from '../lib/live-data.ts';
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const out = resolve(root, 'pages-dist');
const snapshot = JSON.parse(await readFile(resolve(root, 'public/data/current.json'), 'utf8'));
validateSnapshot(snapshot);
await mkdir(resolve(out, 'assets'), { recursive: true });
await mkdir(resolve(out, 'data'), { recursive: true });
const cssDir = resolve(root, 'dist/client/_next/static/css');
const cssFiles = (await readdir(cssDir)).filter(f => f.endsWith('.css'));
if (!cssFiles.length) throw new Error('Run npm run build first');
const css = (await Promise.all(cssFiles.map(f => readFile(resolve(cssDir, f), 'utf8')))).join('\n');
const cssName = 'style-' + createHash('sha256').update(css).digest('hex').slice(0, 12) + '.css';
await writeFile(resolve(out, 'assets', cssName), css);
const result = await build({ absWorkingDir: root, entryPoints: ['scripts/live-entry.tsx'], bundle: true, outdir: resolve(out, 'assets'), entryNames: 'app-[hash]', metafile: true, platform: 'browser', format: 'iife', minify: true, jsx: 'automatic', target: ['es2022'], define: { 'process.env.NODE_ENV': '"production"' }, tsconfig: resolve(root, 'tsconfig.json') });
const jsName = basename(Object.keys(result.metafile.outputs).find(name => name.endsWith('.js')));
const origin = 'https://tangdankang.github.io/coastal-typhoon-watch/';
const html = `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>岸风 · 台风实况与路径</title><meta name="description" content="查看浙江公开台风数据、观测路径、移动方向与风力。每小时同步，非官方信息汇总，不替代官方预警。"><link rel="canonical" href="${origin}"><meta property="og:type" content="website"><meta property="og:locale" content="zh_CN"><meta property="og:url" content="${origin}"><meta property="og:title" content="岸风 · 台风实况与路径"><meta property="og:description" content="公开数据 · 每小时同步。非官方信息汇总，不替代官方预警。"><meta property="og:image" content="${origin}og-live.png"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="岸风 · 台风实况与路径"><meta name="twitter:description" content="公开数据 · 每小时同步。非官方信息汇总，不替代官方预警。"><meta name="twitter:image" content="${origin}og-live.png"><link rel="icon" href="./favicon.svg"><link rel="stylesheet" href="./assets/${cssName}"></head><body><noscript>本页需要 JavaScript 显示数据。请直接访问 <a href="https://typhoon.slt.zj.gov.cn/">浙江省台风路径实时发布系统</a>；本站不是官方预警服务。</noscript><div id="root"></div><script defer src="./assets/${jsName}"></script></body></html>`;
await writeFile(resolve(out, 'index.html'), html);
await writeFile(resolve(out, '.nojekyll'), '');
await copyFile(resolve(root, 'public/data/current.json'), resolve(out, 'data/current.json'));
await copyFile(resolve(root, 'public/og-live.png'), resolve(out, 'og-live.png'));
await copyFile(resolve(root, 'public/favicon.svg'), resolve(out, 'favicon.svg'));
await copyFile(resolve(root, '../网页演示/index.html'), resolve(out, 'demo.html'));
console.log('GitHub Pages static artifact generated. Snapshot: ' + snapshot.fetchedAt);
