import assert from 'node:assert/strict';
import { readFile, readdir, stat } from 'node:fs/promises';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { validateSnapshot, freshness } from '../lib/live-data.ts';
const root = resolve(dirname(fileURLToPath(import.meta.url)), '../pages-dist');
const html = await readFile(resolve(root, 'index.html'), 'utf8');
assert.match(html, /<title>岸风 · 台风实况与路径<\/title>/);
assert.match(html, /https:\/\/tangdankang.github.io\/coastal-typhoon-watch\/og-live.png/);
assert.doesNotMatch(html, /仅演示使用|DEMO ONLY|chatgpt.site|\/node_modules\//);
for (const match of html.matchAll(/(?:href|src)="\.\/([^"#]+)"/g)) assert.ok((await stat(resolve(root, match[1]))).isFile());
const snapshot = JSON.parse(await readFile(resolve(root, 'data/current.json'), 'utf8'));
validateSnapshot(snapshot);
assert.equal(freshness(snapshot.fetchedAt).snapshotStale, false, 'Do not publish an already-stale snapshot');
assert.doesNotMatch(JSON.stringify(snapshot), /DEMO-|青岚|云汐/);
assert.match(await readFile(resolve(root, 'demo.html'), 'utf8'), /仅.*演示/);
const allowed = new Set(['.nojekyll', 'index.html', 'demo.html', 'favicon.svg', 'og-live.png', 'assets', 'data']);
for (const name of await readdir(root)) assert.ok(allowed.has(name), 'Unexpected public artifact: ' + name);
console.log('Static artifact verified: correct project-relative assets, live metadata, fresh validated snapshot, and separate demo.');
